### ISSUE TITLE
file does not have EXIF

### ISSUE THREAD

**Issue by geocine** [dsoprea/go-png-image-structure#2]
I am getting this error `file does not have EXIF` , here is my code

```go
pmp := pngstructure.NewPngMediaParser()
cs, _ := pmp.ParseFile(filePath)
_, rawExif, exifErr := cs.Exif()
    if exifErr != nil {
    return nil, exifErr
}

print(rawExif)
```
Here is my png. I ran this against `exiftool.exe` and I can see the metadata

![dinosaur](https://user-images.githubusercontent.com/507464/211167276-7a343a6a-ba01-4d1b-b094-82f6746b5335.png)

You should be able to download this and see the exif using `exiftool.exe` . I am mainly concerned about retrieving the `Parameters`

```
ExifTool Version Number         : 12.49
File Name                       : 211167276-7a343a6a-ba01-4d1b-b094-82f6746b5335.png
Directory                       : .
File Size                       : 481 kB
Zone Identifier                 : Exists
File Modification Date/Time     : 2023:01:08 03:26:35+08:00
File Access Date/Time           : 2023:01:08 03:26:44+08:00
File Creation Date/Time         : 2023:01:08 03:26:34+08:00
File Permissions                : -rw-rw-rw-
File Type                       : PNG
File Type Extension             : png
MIME Type                       : image/png
Image Width                     : 512
Image Height                    : 512
Bit Depth                       : 8
Color Type                      : RGB
Compression                     : Deflate/Inflate
Filter                          : Adaptive
Interlace                       : Noninterlaced
Parameters                      : zwx artstyle, a (dinosaur), (stone carving), intricate background texture,  furnished, detailed stone carving, stone art, [[gold outlines]], colorful accents, global illumination, masterpiece, award winning, (square frame).Negative prompt: disfigured, bright, blur, haze, low quality, (((hollow))), shadows, void,  ((out of frame)) , plain, circle, circular.Steps: 100, Sampler: Euler a, CFG scale: 8, Seed: 2693542571, Size: 512x512, Model hash: b28fcc50
Image Size                      : 512x512
Megapixels                      : 0.262
```

**Comment by muellerkyle** [comment]
Something that you may be interested in: https://stackoverflow.com/questions/9542359/does-png-contain-exif-data-like-jpg

Specifically:

> Edit: Version 1.5.0 (July 2017) of the [Extensions to the PNG 1.2 Specification](http://ftp-osl.osuosl.org/pub/libpng/documents/pngext-1.5.0.html#C.eXIf) has finally added an EXIF chunk. It remains to be seen if encoders-decoders begin to support it.

> Original: PNG does not embed EXIF info. It allows, however, to embed metadata "[chunks](http://www.w3.org/TR/PNG/#11Chunks)" inside the image. Some of the [standardized chunks](http://en.wikipedia.org/wiki/Portable_Network_Graphics#Ancillary_chunks) correspond to a few EXIF attributes (physical dimensions, timestamp). And it's also possible to store arbitrary textual data as key=>value pairs, or to define new chunk types. So, you could in theory store any EXIF information... but, alas, in your own custom format. Some [attempts](http://pmt.sourceforge.net/exif/drafts/d020.html) to standarize have not caught up, it seems.

I, like you, was under the impression that Exif data was part of the PNG spec. But, this seems that it is relatively new and it's possible that the embedded data that `exiftool` is reading isn't Exif encoded. It's probably in chunks.

This library does appear to have chunk reading capabilities. Have you tried those?

**Comment by jrstrunk** [comment]
It looks like your png file wrote its metadata to a tEXt chunk, which can be parsed with this library as @muellerkyle alluded to. This go program:
```
package main

import (
	"fmt"

	pngstructure "github.com/dsoprea/go-png-image-structure/v2"
)

func main() {
	pmp := pngstructure.NewPngMediaParser()

	intfc, err := pmp.ParseFile("211167276-7a343a6a-ba01-4d1b-b094-82f6746b5335.png")
	if err != nil {
		panic(err)
	}

	cs := intfc.(*pngstructure.ChunkSlice)

	index := cs.Index()

	fmt.Printf("tEXt data: \"%s\"\n", index["tEXt"][0].Data)
}
```
produces this output:
`tEXt data: "parameterszwx artstyle, a (dinosaur), (stone carving), intricate background texture,  furnished, detailed stone carving, stone art, [[gold outlines]], colorful accents, global illumination, masterpiece, award winning, (square frame)
Negative prompt: disfigured, bright, blur, haze, low quality, (((hollow))), shadows, void,  ((out of frame)) , plain, circle, circular
Steps: 100, Sampler: Euler a, CFG scale: 8, Seed: 2693542571, Size: 512x512, Model hash: b28fcc50"`.

The tEXt chunk uses the `0`, or `NUL` UTF-8 character as the separator between property name and value, so when it is converted to a string it will look like there is no seperator at all, thus why you get `parameterszwx ...` instead of something like `parameters:zwx ...`. Before casting to a string, you can parse the bytes slice to get key value pairs based on the placement of the `NUL` character in the tEXt chunk.
